# .goreleaser.yaml
builds:
- env:
  - CGO_ENABLED=0
  binary: mybin
  goos:
  - linux
  goarch:
  - amd64
  - arm64
dockers:
- image_templates:
  - "waterlemons2k/test:{{ .Version }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "waterlemons2k/test:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: "waterlemons2k/test:{{ .Version }}"
  image_templates:
  - "waterlemons2k/test:{{ .Version }}-amd64"
  - "waterlemons2k/test:{{ .Version }}-arm64v8"