name: Cache

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/cache.yml'
      
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: touch ~/.cache
        
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache
          key: Cache
