name: Cache

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/cache.yml'
      
jobs:
  cache:
    uses: WaterLemons2k/workflows/.github/workflows/cache.yml@main
    with:
      run: echo $RANDOM
