name: Docker

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/docker.yml'
      - 'Docker/**'
      
env:
  NAME: hello-world #镜像名称
      
jobs:
  docker:
    uses: WaterLemons2k/Docker/.github/workflows/docker.yml@main
    with:
      context: Docker
      tags: waterlemons2k/test:${{ env.NAME }}
    secrets:
      TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
