name: Docker

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/docker.yml'
      - 'Docker/**'
      
jobs:
  docker:
    uses: WaterLemons2k/Docker/.github/workflows/docker.yml@main
    with:
      context: Docker
      platforms: amd64,arm,arm64
      tags: |
        waterlemons2k/test
        waterlemons2k/test:hello-world
      description: true
      description-repository: waterlemons2k/test
    secrets:
      TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
