name: Docker

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/docker.yml'
      - 'Docker/**'
      
jobs:
  docker:
    uses: WaterLemons2k/Docker/.github/workflows/docker.yml@main
    with:
      context: Docker
      platforms: amd64,arm,arm64
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      meta-images: waterlemons2k/test
      description-repository: waterlemons2k/test
    secrets:
      TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
