name: Docker Meta

on:
  push:
    paths:
      - '.github/workflows/docker-meta.yml'

jobs:
  docker-meta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Meta
        uses: docker/metadata-action@v4
        with:
          images: waterlemons2k/test

      - name: Build
        uses: docker/build-push-action@v4
        with:
          build-args: ${{ env.DOCKER_METADATA_OUTPUT_JSON }}