name: Docker

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/docker.yml'
      - 'Docker/**'
      
jobs:
  docker:
    uses: WaterLemons2k/Docker/.github/workflows/docker.yml@main
    with:
      context: Docker
      tags: waterlemons2k/test:hello-world
    secrets:
      TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
