name: Git

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
    paths:
      - '.github/workflows/git.yml'
      
jobs:
  git:
    uses: WaterLemons2k/workflows/.github/workflows/git.yml@main
    with:
      run: |
        date '+%F %X' > DATE
        cat DATE
      commit_message: "feat: add DATE"
