name: GoReleaser

on:
  push:
    paths:
      - '.github/workflows/goreleaser.yml'
      - 'Go/**'
      
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Set up Go
        uses: actions/setup-go@v4
        
      - name: No push tag
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean ${{ env.flags }}
          workdir: Go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
