name: If env

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/if-env.yml'
      
#设置变量 FOO
env:
  FOO: true
      
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Output env FOO
        if: env.FOO == 'true' #如果变量 FOO 的值为 true
        run: echo ${{ env.FOO }} #输出变量 FOO 的值
