name: Summary

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/summary.yml'

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Add summary
        run: |
          {
            echo "# Summary"
            echo "Date: \`$(date)\`"
            echo "Directory: \`$PWD\`"
            echo "Repository: \`${{ github.repository }}\`"
            echo "Workflow: \`${{ github.workflow }}\`"
            echo "Branch: \`${{ github.ref_name }}\`"
          } >> $GITHUB_STEP_SUMMARY
