name: uses workflow_call

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/uses-workflow_call.yml'
      - '.github/workflows/workflow_call.yml'
      
jobs:
  uses:
    uses: ./.github/workflows/workflow_call.yml