#https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_call
#https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: workflow_call

on:
  workflow_call:
    inputs:
      boolean:
        default: true
        required: false
        type: boolean
      number:
        default: 1
        required: false
        type: number
      string:
        default: 'string'
        required: false
        type: string
      command:
        default: "date"
        required: false
        type: string
        
    secrets:
      token:
        required: false
        
jobs:
  workflow_call:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input to STDOUT
        run: |
          echo The boolean is ${{ inputs.boolean }}
          echo The number is ${{ inputs.number }}
          echo The string is ${{ inputs.string }}
          echo "The command output is $(${{ inputs.command }})"
